### ISSUE TITLE
WP-CLI binary not found on wordpress-cms template

### ISSUE THREAD

**Issue by lorenzorivosecchi** [a-barbieri/fastline#9]
## Steps to reproduce the issue

- Copy contents of `templates/wordpress-cms/config` into a new folder
- Replace variables manually
- Run `docker-compose up`

## Error
```
web_1  | ./wp_install.sh: 18: ./wp_install.sh: wp: not found
web_1  | ./wp_install.sh: 24: ./wp_install.sh: wp: not found
```

## Solution
Remove wp_install.sh from command inside `docker-compose.yml.services.web`.
As it happened to me, the error will go away and wordpress files will appear inside the web folder.

```yml
version: "3.7"

services:
  web:
    build: ./web
    command: bash -c 'apache2-foreground'
```
